class Exceptiona
{
public static void main(String[] args)
String str= null;
int num1, num2=0;
num1=0;
try
num2=62/num1;
catch(ArithmeticException e)
System.out.println("You should not divide a number by zero");
System.out.println(num2);
System.out.println("Hey I'm at the end of first try block");
try
System.out.println(str.length());
catch(NullPointerException e)
System.out.println("You should not calculate length of null string");
catch(Exception e)
System.out.println("Exception occured");
System.out.println("I'm out of try catch block in java");
}
